### ISSUE TITLE
train with multiple gpus

### ISSUE THREAD

**Issue by KushinaYu** [ioangatop/srVAE#2]
Hi! When I run the code with 2 or 3 gpus, the program will turn into Sl+ process. Do you know the reason?

**Comment by ioangatop** [comment]
Hello! I also trained on multiple gpus, but never had this issue. Can you please elaborate on the `Sl+ process`? I am not familiar with it. Thanks!

**Comment by KushinaYu** [comment]
The program is stopped and waiting for an event to complete for Sl+ process . Do you use the conmmand such as`  CUDA_VISIBLE_DEVICES=0,1 python main.py --model srVAE --network densenet16x32 --prior RealNVP` to run the code with cifar10 or celeba? Thanks!

**Comment by ioangatop** [comment]
As the model (by default in the `main.py` file) is wrapped in the `nn.DataParallel` module, by simply running `python main.py --model srVAE --network densenet16x32 --prior RealNVP` should activate all available `cuda` devices (on `/src/utils/args.py` the program checks automatically if any `cuda` devices are available).

However, I did use the command `CUDA_VISIBLE_DEVICES=1 python main.py --model srVAE --network densenet16x32 --prior RealNVP` to specifically choose only one gpu.

Please try the two above commands and check if they work as expected 🙂.

**Comment by KushinaYu** [comment]
Hi!&nbsp;I want to know if I change the scale_factor=4, do I need to change it to in_channels *= 4 in the red box below? And is there anything else in the code that needs to be changed?
Thanks!&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ioangatop/srVAE"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月16日(星期四) 下午2:54
收件人:&nbsp;"ioangatop/srVAE"<srVAE@noreply.github.com&gt;;
抄送:&nbsp;"コナンの嫁"<2435142508@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ioangatop/srVAE] train with multiple gpus (#2)





 
Closed #2.
