### ISSUE TITLE
where is  model.module.initialize(train_loader)?

### ISSUE THREAD

**Issue by liunangithub** [ioangatop/srVAE#3]
in the main.py ,I can't find where the  initialize() come from? Could you please help me ? Because it has hindered me in understanding this codes right along.

**Comment by ioangatop** [comment]
If you use, for example the VAE, is the following module:

https://github.com/ioangatop/srVAE/blob/94d2481d395a1ad2584790e5de038123ccc34888/src/models/vae/vae.py#L51-L60

This performs a forward pass, that triggers the `init_parameters` of `Conv2d` class:

https://github.com/ioangatop/srVAE/blob/94d2481d395a1ad2584790e5de038123ccc34888/src/modules/nn_layers.py#L66

**Comment by liunangithub** [comment]
ok，thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ioannis Gatopoulos"<notifications@github.com&gt;; 
发送时间: 2020年8月27日(星期四) 晚上9:54
收件人: "ioangatop/srVAE"<srVAE@noreply.github.com&gt;; 
抄送: "2197331789"<2197331789@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ioangatop/srVAE] where is  model.module.initialize(train_loader)? (#3)





 
If you use, for example the VAE, is the following module:
 
https://github.com/ioangatop/srVAE/blob/94d2481d395a1ad2584790e5de038123ccc34888/src/models/vae/vae.py#L51
 
This performs a forward pass, that triggers the init_parameters of Conv2d class:
 
https://github.com/ioangatop/srVAE/blob/94d2481d395a1ad2584790e5de038123ccc34888/src/modules/nn_layers.py#L66
