### ISSUE TITLE
how to execute the code use one GPU?

### ISSUE THREAD

**Issue by liunangithub** [ioangatop/srVAE#4]
Hello, there are multi-gpu in your code , can I change the code to adapt only one GPU？And How ?because I only have one GPU.

**Comment by ioangatop** [comment]
Hi, there are different ways to do it:

- Try to start the code with the following command: `CUDA_VISIBLE_DEVICES=1 python main.py`. This `1` refers to the specific GPU that you want to use. Try with 0, 1 etc, depending with your set up.

- Remove the `nn.DataParallel` wrap from the model. Specifically, try to replace the line 
https://github.com/ioangatop/srVAE/blob/4704daa1fd24858d93aedc0ec128569a395a7189/main.py#L20
with
```
model = globals()[model](data_shape).to(args.device)
```
This will only use the first GPU of your setup.

**Comment by liunangithub** [comment]
Thank you for helping me address this problem.
